### ISSUE TITLE
Is it possible to render models and textures directly

### ISSUE THREAD

**Issue by axb996** [Lime-blur/rwparser#4]
There may be some anomalies in the conversion, such as some models cannot be converted, the structure of the converted model is abnormal, etc. I wonder whether it is possible to directly preview the real-time rendering model and map? Can support functions like zmod, but without editing capabilities.

**Comment by Lime-blur** [comment]
Hello! Can you please tell, what you mean by “model map”?

**Comment by SimoSbara** [comment]
> There may be some anomalies in the conversion, such as some models cannot be converted, the structure of the converted model is abnormal, etc. I wonder whether it is possible to directly preview the real-time rendering model and map? Can support functions like zmod, but without editing capabilities.

Could you please send the model which you are having issue in the conversion?

Just to be clear dff_converter library provides functionality for DFF +TXD conversion to GLTF, it doesn't provide any render capabilities, it is not a 3d modeling viewer/editor, it's just a conversion tool.

**Comment by Lime-blur** [comment]
> > There may be some anomalies in the conversion, such as some models cannot be converted, the structure of the converted model is abnormal, etc. I wonder whether it is possible to directly preview the real-time rendering model and map? Can support functions like zmod, but without editing capabilities.
> 
> 
> 
> Could you please send the model which you are having issue in the conversion?
> 
> 
> 
> Just to be clear dff_converter library provides functionality for DFF+TXD conversion to GLTF, it doesn't provide any render capabilities, it is not a 3d modeling viewer/editor, it's just a conversion tool.

By the way, I agree. The dff_converter library really only does the conversion. As for the rwparser library, it can both convert and analyse dff and txd files. Thus, with the help of the library, you can analyse and convert game models into a convenient format for rendering in Android applications, as implemented in the [MTA:SA Developers: Mobile](https://play.google.com/store/apps/details?id=ru.limedev.mtacse) application.

**Comment by Lime-blur** [comment]
> This is the model I tested for conversion, if converting dff and txd at the same time, the converted gltf file is corrupted. If only dff files are converted, the converted gltf model appears distorted. In addition, part of the original dff model extracted from the game gta3.img file can be converted, some can not be converted (such as bus car model), this is the library can not handle? I wonder if [the other library](https://github.com/davidar/dff2gltf) I saw could help.
> 
> 
> 
> [test.zip](https://github.com/user-attachments/files/17495114/test.zip)
> 
> 

Your archive contains ifp files and one txd file. What do you want to convert it into?

**Comment by SimoSbara** [comment]
> This is the model I tested for conversion, if converting dff and txd at the same time, the converted gltf file is corrupted. If only dff files are converted, the converted gltf model appears distorted. In addition, part of the original dff model extracted from the game gta3.img file can be converted, some can not be converted (such as bus car model), this is the library can not handle? I wonder if [the other library](https://github.com/davidar/dff2gltf) I saw could help.
> 
> [test.zip](https://github.com/user-attachments/files/17495114/test.zip)

IFP are animation files, maybe you sent the wrong zip archive? 
I tested the dff_converter with all gta san andreas skins with success, it should be compatible also with vice city and gta 3. 

Can you explain better what are you trying to convert? Vehicles? Objects? Skins?

**Comment by SimoSbara** [comment]
> > > 这是我测试的模型，如果同时转换dff和txd，转换出来的gltf文件会损坏。如果只转换dff文件，转换出来的gltf模型会出现扭曲。另外，从游戏gta3.img文件中提取出原始dff模型有一部分可以转换，有一部分不能转换（比如转换模型），这个是库不能处理的吗？不知道我看到的[其他库](https://github.com/davidar/dff2gltf)能不能帮上忙。
> > > [测试版](https://github.com/user-attachments/files/17495114/test.zip)
> > 
> > 
> > IFP 是动画文件，也许你发送了错误的 zip 文档？ 我成功地用所有 gta san andreas 皮肤测试了 dff_converter，它也应该与 Vice City 和 gta 3 兼容。
> > 你能更详细地解释一下你想转换什么吗？车辆？物体？皮肤？
> 
> I converted the mobile version of GTASA, but some of the characters and car models extracted from GTA 3.IMGA cannot be converted. Did you test the mobile version?

I tried to convert gangrl1.dff and this is what I got:
![model](https://github.com/user-attachments/assets/1ec200be-6169-4914-84b1-3acf54193ee6)

All the model parts are converted correctly but there are some issues in the hair, I need to investigate more but this isn't a native gta sa model for sure.

**Comment by Lime-blur** [comment]
> Yes, that's it. Then why can't some characters and vehicles extracted from 【gta3.img】 in Android games be converted? Is the Android model encrypted? By the way, can the library extract model images from the txt cache?

The library can't retrieve images. Only get a dump. As for Android models, maybe yes, they are encrypted, but I can't say for sure. In any case, I can say for sure that Android models are definitely different from regular ones.

**Comment by Lime-blur** [comment]
Since there were no more comments from the author, I close this issue. If you have any questions, you can always create a new issue.
